### ISSUE TITLE
Random server crashes

### ISSUE THREAD

**Issue by iAverages** [tr7zw/YAPFA#269]
I'm honestly not sure why this keeps happening and I can't seem to find what might cause this issue so I'll post something here and hope someone can help / lead me in the right direction (Assuming this is an issue on my end / a plugin)

A server I manage recently started crashing early in the morning because the server thread was locking up and Watchdog shut the server. I've spent some time looking into the issue and have no idea why or what might cause this to happen. I spoke to the dev of TAB (with the dump that mentioned TAB) and he said java failed to create a thread but no idea why. I'm not sure if it's a plugin issue or and issue on the dedi the server is hosted on. This is my last resort to find the problem / possible solution. 

If I shouldn't post this here, please let me know and I'll look elsewhere for help. 

Thread dumps: 

- 21/10/2020 06:55:07 CET
   Partial: https://paste.danielraybone.com/uzibudupak.hs
   Full: https://paste.danielraybone.com/unugapemez.hs
- 23/10/2020 07:01:04 CET
   Partial: https://paste.danielraybone.com/uyahapojey.hs
   Full: https://paste.danielraybone.com/ujebozugim.hs
- 24/10/2020 06:46:56 CET
   Partial: https://paste.danielraybone.com/ebemevowiq.hs
   Full: https://paste.danielraybone.com/kilizoxale.hs
- 25/10/2020 06:23:35 CET
   Partial: https://paste.danielraybone.com/uqidunetin.hs 
   Full: https://paste.danielraybone.com/okiyiviril.hs
- 26/10/2020 04:24:35 CET
   Partial: https://paste.danielraybone.com/wasusutesi.hs
   Full: https://paste.danielraybone.com/apipatanub.hs
- 26/10/2020 22:24:54 CET
   Partial: https://paste.danielraybone.com/uxoqudinef.hs
   Full: n/a

**Installed plugins**

[removed]

**Version**

![version](https://dannn.net/CSmqfdzx)

**Comment by duplexsystem** [comment]
Can we have a timings report please?

**Comment by MrIvanPlays** [comment]
crash from 21: Database connection failure, connection was requested by FastLogin ( or FastLogin making AuthMe ) to save the quitting player's data.
crash from 23: I have 0 idea of why the JVM wasn't able to create a thread, but I've seen such things with machines having I/O problems.
crash from 24: I/O issue. InventoryRollback tried to load data from a file but failed.
crash from 25: same as 24. Seeing database connection failures here too.
crash from 26 04:24:35 CET: I/O issue. InventoryRollback tried to save data to a file but failed. Seeing database connection failures here too.
crash from 26 22:24:54 CET: Now that's weird. The code involved here is trying to loop thru some data, but fails for some unexpected reason. Will need a full thread dump tho in order to properly realise whats going on. 

As budgidiere mentioned too, I'd also like a timings report (if you are able to capture any).

Overall you have database connection problems, and I/O problems.

**Comment by iAverages** [comment]
crash from 26 22:24:54 CET wasn't a full crash, it started to timeout but came back, just a massive lag spike on the server. 

Here's a timings report from just now. I haven't been able to get any from before the server crashed since they've been at random times during the night. If the server has a massive lag spike again (what happed at 26 22:24:54 CET) then I'll grab a timings report after that. 
**timings:** https://timings.aikar.co/?id=bbebbcec53ba4898801878a32f8b1ac8

I had a feeling it was an I/O issue but wasn't too sure as I have no idea how to read a thread dump, but that helps a lot so thank you.

**Comment by MrIvanPlays** [comment]
I see very good timings.
If you need any more suport with lags join our discord. I/O issues and database connection issues are something that is out of our scope.
