### ISSUE TITLE
Villagers do not breed

### ISSUE THREAD

**Issue by nowfow** [tr7zw/YAPFA#464]
**Expected behavior**
Villagers do not reproduce, hearts just come from them and that's it

**Steps to reproduce (if known)**
It is necessary to give the villagers the necessary items for breeding and wait

**Installed plugins**
Plugins {0}

**Version**
This server is running Yatopia version git-Yatopia-ver/1.16.5-79 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Video: https://youtu.be/ZJEBPfxRi-U

**Comment by toinouH** [comment]
@nowfow could you provide timings so we can know what are your settings ?

**Comment by t0ssox** [comment]
They don't breed because you don't know how to do this properly. To breed them they need to have a job (what they already have looking at your video) and **you need to place beds for them and one more extra for child.** Remember to give a 2 blocks of free space above beds for the villagers AI to see them. It's not a Yatopia bug.

**Comment by nowfow** [comment]
beds were needed for breeding
