### ISSUE TITLE
Execute command doesn't work

### ISSUE THREAD

**Issue by NovaPixell** [tr7zw/YAPFA#8]
Hi, I'll point out a problem I'm experiencing.
The command "/execute as @a[nbt={Inventory:[]}] run tellraw YOURNICKNAME ["",{"text":"Entity: "},{"selector":"@s"}]" if typed gives as output a list of players who have empty inventory. Except that with your software it doesn't work, I'm sure because I did some tests.
Can you tell me if I have to change something or if it is a problem that you can fix?
Good day

**Comment by tr7zw** [comment]
Ok, can confirm that this seems to work on Tuinity but not Yapfa. ~~Kinda odd since nothing should be changed there. ``/execute as @a[name=tr7zw] run say test`` and ``/execute as @a[gamemode=creative] run say test`` booth seem to work while ``/execute as @a[nbt={Inventory:[]}] run say test`` doesn't.~~

Just remembered: I made that Player saving is done somewhat async, but the inventory and enderchest are precached sync to prevent dupe bugs. The execute as command probably wasn't directly in the src, so I didn't see that it also uses this method. I'll change to logic to grab the inventory/enderchest if they aren't precached in order to not break other methods that expect the method to also contain the inventory.

**Comment by NovaPixell** [comment]
Ah perfect. So are you able to solve it? Sorry if I'm breaking you up, but I'm working for a Vanilla server of a well-known youtuber / streamer. haha

**Comment by tr7zw** [comment]
``Sorry if I'm breaking you up, but I'm working for a Vanilla server of a well-known youtuber / streamer. haha`` same xD So I know that feel. Also yes the newest build has it fixed (build #96). Also feel free to join the discord (https://discord.com/invite/yk4caxM) for quicker text exchanges^^.

**Comment by NovaPixell** [comment]
Perfect, thank you very much indeed!
